start_epoch: 0
gpu_id: 0
load_headnerf_checkpoint: 'checkpoints/xyl/headnerf_latest'
lr_deform_vol: 1e-2
lr_feat_vol: 1e-2
lr_deform_net: 1e-3
lr_feat_net: 1e-3
batch_size: 1

dataset:
  dataroot: 'demo_dataset'
  video_name: 'xyl'
  resolution: 256

headmodule:
  deform_bs_res: 32
  deform_bs_dim: 2
  deform_linear: [54, 128, 3]
  feature_res: 64
  feature_dim: 4
  density_linear: [140, 128, 1]
  color_linear: [167, 128, 3]
  exp_dim: 32
  interp_level: 3
  embedding_freq: 4
  deform_bbox: [[-1.1, 1.1], [-1.1, 1.4], [-1.0, 0.9]]
  feature_bbox: [[-1.2, 1.2], [-1.1, 1.6], [-1.8, 0.9]]
  noise: 0.0
  
neuralcamera:
  model_bbox: [[-1.2, 1.2], [-1.1, 1.6], [-1.8, 0.9]]
  image_size: 256
  max_samples: 4096
  N_samples: 0
  N_importance: 64
  near_far: [3.5, 4.5]

recorder:
  name: 'xyl'
  logdir: 'log/xyl'
  checkpoint_path: 'checkpoints'
  result_path: 'results'
  save_freq: 1000
  show_freq: 10
